language: c
#######################################################################################
os:
  - linux
  
sudo: enabled

addons:
  apt:
    packages:
      - curl

#######################################################################################


before_install:

  - sudo apt-get update -qq
  
  - git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 ~/aarch64-linux-android-4.9/
  
  - sudo chmod -R a+x *

#######################################################################################


script:  
  
  - export ARCH=arm64
  - export ARCH_MTK_PLATFORM=mt6753
  - export CROSS_COMPILE=~/aarch64-linux-android-4.9/bin/aarch64-linux-android-
  
  - KERNEL_DIR=$PWD/android_kernel_gionee_wbl7511
  - ZIMAGE=$KERNEL_DIR/arch/arm64/boot/zImage
  - mkdir -p out
  - make O=out clean
  - make O=out mrproper
  - make O=out gionee6753_65u_m0_defconfig
  - make O=out -j16

after_success:
  - curl --upload-file arch/arm64/boot/zImage https://transfer.sh/kernel
  
deploy:
  skip_cleanup: true
  provider: releases
  api_key: "$GitOAUTHToken_KERNEL"
  
  on:
    tags: true
    repo: ALGPHELLO/android_kernel_gionee_wbl7511
    branch: master

branches:
  except:
- /^(?i:untagged)-.*$/
